# Generated by Django 3.2 on 2023-04-15 11:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Не выполнен'), (2, 'Выполнен'), (3, 'Отказ')], default=1, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('send_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDayRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recomend_rating', models.PositiveSmallIntegerField(choices=[(1, 'Не работал'), (2, 'Очень плохо'), (3, 'Плохо'), (4, 'Хорошо'), (5, 'отлично')], default=1)),
                ('date', models.DateField(default=datetime.date.today)),
                ('rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Не работал'), (2, 'Очень плохо'), (3, 'Плохо'), (4, 'Хорошо'), (5, 'отлично')], null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True)),
                ('comment', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
